name: smart_flare
description: A package that helps with larger flare animations and interactions.
version: 0.2.10
homepage: https://github.com/FilledStacks/smart_flare

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^3.0.2

dev_dependencies:

flutter: